title: r/steroids wiki
email: JuiceLoosener@protonmail.com

# Build settings
markdown: kramdown
remote_theme: zendesk/jekyll-theme-zendesk-garden@main
sidebar:
  - overview
    - overview-faq
    - overview-rules
  - planning
    - cycles-injecting
    - cycles-pct
