title: r/steroids wiki
email: JuiceLoosener@protonmail.com

# Build settings
markdown: kramdown
remote_theme: zendesk/jekyll-theme-zendesk-garden@main
search_enabled: true
sidebar:
  - label: Getting Started
    children:
      - gettingstarted-index
      - gettingstarted-rules
      - gettingstarted-reading
  - label: Compounds
    children:
      - compounds-index
      - compounds-anadrol
      - compounds-anavar
