title: r/steroids wiki
email: JuiceLoosener@protonmail.com

# Build settings
markdown: kramdown
remote_theme: zendesk/jekyll-theme-zendesk-garden@main
search_enabled: true
sidebar:
  - overview
  - cycles
  - compounds
  - estrogen
  - sides
  - bloodwork
  - homebrew
